CC = g++
CFLAGS = -std=c++11
FILE_NAME = main.cpp
LINK_FLAGS =  -lpthread
EXECUTABLE_FILE = ‫‪PhonePricePrediction.out‬‬

target:
	$(CC) $(CFLAGS) $(FILE_NAME) $(LINK_FLAGS) -o $(EXECUTABLE_FILE)

clean:
	rm -rf *.o *.out
